# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img_question',
            field=models.FileField(blank=True, null=True, upload_to='question_img'),
        ),
    ]
