# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_type',
            field=models.CharField(choices=[('QCM', 'Multiple Choice'), ('ES', 'Essay'), ('TF', 'True False')], default='QCM', max_length=1),
        ),
    ]
