# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.TextField(max_length=250),
        ),
    ]
