# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_name',
        ),
    ]
