# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_auto_20180705_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
