# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_auto_20180702_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='option_name',
        ),
    ]
