# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_auto_20181106_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='img_option',
            new_name='img_question',
        ),
    ]
