# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_auto_20180808_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.Question'),
        ),
    ]
