# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_auto_20180611_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='answer',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_type',
            field=models.CharField(choices=[('QCM', 'Multiple Choice'), ('ES', 'Essay')], default='QCM', max_length=1),
        ),
    ]
