# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_option_img_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='img_option',
            field=models.FileField(null=True, upload_to='question_options'),
        ),
    ]
