# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0003_auto_20180611_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest_type',
            field=models.CharField(choices=[('QCM', 'Multiple Choice'), ('ES', 'Essay')], default='QCM', max_length=3),
        ),
    ]
