# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0004_auto_20181011_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_option',
            field=models.FileField(blank=True, null=True, upload_to='question_img'),
        ),
        migrations.AlterField(
            model_name='option',
            name='img_option',
            field=models.FileField(blank=True, null=True, upload_to='option_img'),
        ),
    ]
