# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0004_auto_20180612_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='create_test',
            new_name='test_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='update_date',
        ),
    ]
