# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0005_auto_20181011_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
