# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=120)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('phonenumber', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(max_length=120)),
                ('file', models.ImageField(upload_to=b'profile_image')),
                ('image', models.ImageField(upload_to=b'card_image')),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
    ]
