# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='images',
            new_name='file',
        ),
    ]
