# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
