# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0003_auto_20180808_2150'),
        ('register', '0004_videoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Register')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.Question')),
            ],
        ),
    ]
