# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_candidateanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateanswer',
            old_name='answer',
            new_name='essay_answer',
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='selected_option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
