# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180918_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
