# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_register_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='taken_test',
            field=models.BooleanField(default=False),
        ),
    ]
